# Generated by Django 2.1.2 on 2018-12-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendtrackapp', '0003_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='leaf_category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, related_name='leaf_category', to='spendtrackapp.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spendtrackapp.Category'),
        ),
    ]
